import indentString from 'indent-string'

export const termsText1 = `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non.Vivamus arcu felis bibendum ut tristique et egestas quis ipsum.Facilisi etiam dignissim diam quis.Nunc scelerisque viverra mauris in aliquam sem fringilla.Amet est placerat in egestas erat imperdiet sed euismod nisi.Pulvinar pellentesque habitant morbi tristique senectus et.Mi proin sed libero enim sed faucibus.Enim sed faucibus turpis in eu.Vulputate ut pharetra sit amet aliquam.Ipsum suspendisse ultrices gravida dictum fusce.Mauris a diam maecenas sed enim ut sem viverra aliquet.Nulla facilisi morbi tempus iaculis urna id.Blandit volutpat maecenas volutpat blandit.Porta nibh venenatis cras sed felis eget velit.`

export const termsText2 = `Scelerisque varius morbi enim nunc faucibus a pellentesque.Aliquam eleifend mi in nulla posuere sollicitudin aliquam.Eu mi bibendum neque egestas congue quisque.Volutpat lacus laoreet non curabitur gravida arcu ac.Sed id semper risus in.Elementum integer enim neque volutpat ac tincidunt.Congue quisque egestas diam in arcu cursus euismod.Eget sit amet tellus cras adipiscing enim eu turpis egestas.Bibendum est ultricies integer quis auctor elit sed vulputate mi.Curabitur gravida arcu ac tortor dignissim convallis aenean.Nulla porttitor massa id neque aliquam.Nullam ac tortor vitae purus.Senectus et netus et malesuada fames ac turpis egestas.`

export const termsText3 = `At in tellus integer feugiat scelerisque varius.Facilisi nullam vehicula ipsum a arcu cursus vitae congue.At auctor urna nunc id.Lectus proin nibh nisl condimentum id venenatis a.Nullam vehicula ipsum a arcu cursus vitae.Gravida arcu ac tortor dignissim convallis aenean.Ultrices vitae auctor eu augue ut lectus arcu bibendum at.Cras fermentum odio eu feugiat pretium nibh ipsum.Tellus mauris a diam maecenas sed enim ut sem viverra.Est ultricies integer quis auctor elit sed.Elementum integer enim neque volutpat ac tincidunt vitae semper.Mauris in aliquam sem fringilla ut morbi tincidunt augue interdum.`

export const termsText4 = `Quis enim lobortis scelerisque fermentum.Dignissim diam quis enim lobortis scelerisque.Vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat.Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor.Lacus sed turpis tincidunt id aliquet risus feugiat.Nibh cras pulvinar mattis nunc sed blandit libero volutpat sed.Vel facilisis volutpat est velit egestas dui id.Mattis ullamcorper velit sed ullamcorper morbi.Pharetra convallis posuere morbi leo urna molestie.Volutpat est velit egestas dui id ornare arcu odio.Nec sagittis aliquam malesuada bibendum.Enim nec dui nunc mattis enim ut tellus.Pretium aenean pharetra magna ac placerat.Sit amet mattis vulputate enim nulla aliquet porttitor.Vitae aliquet nec ullamcorper sit amet.Lorem sed risus ultricies tristique nulla aliquet enim tortor at.Fringilla est ullamcorper eget nulla facilisi etiam dignissim.`

export const termsText5 = `Egestas quis ipsum suspendisse ultrices gravida dictum fusce.Dignissim enim sit amet venenatis urna.Amet dictum sit amet justo donec enim diam vulputate.Non sodales neque sodales ut etiam sit.Ut enim blandit volutpat maecenas volutpat blandit aliquam etiam erat.Cursus vitae congue mauris rhoncus aenean vel.Adipiscing elit ut aliquam purus sit amet luctus venenatis.Adipiscing bibendum est ultricies integer quis auctor elit sed vulputate.Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend.Cum sociis natoque penatibus et magnis dis parturient montes nascetur.Vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis.Adipiscing bibendum est ultricies integer quis.Vitae auctor eu augue ut lectus.At ultrices mi tempus imperdiet nulla malesuada pellentesque.Egestas fringilla phasellus faucibus scelerisque.Imperdiet proin fermentum leo vel orci.Vestibulum morbi blandit cursus risus.`
